---
version: "3"
services:
  in-stock-bot:
    build: .
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    volumes:
       - "./data:/app/data:rw"
    environment:
      - UID=1000 
      - GID=1000
      - LINK=https://www.bol.com/nl/nl/p/playstation-5-digital-edition-slim-30th-anniversary-limited-edition/9300000190960933/?s2a=&bltgh=okyHMmlgndqy1qPXHT1GFA.2_56_57.58.FeatureListItem#productTitle
      - API_Key=7603615077:AAG_l7Ood5_pvbldm-986ZmzD_P6snMZzw0
      - expected=4
      - unavailabilityMessage=NO
    stdin_open: true
    tty: true
    restart: unless-stopped
